yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler403csrf = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Выберите группу'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Адрес группы',
        help_text='Выберите адрес группы'
    )
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Выберите описание группы'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    objects = None
    text = models.TextField(
        max_length=200,
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        verbose_name='Группа поста',
        related_name='posts',
        blank=True,
        null=True,
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField(
        max_length=200,
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор поста'
    )
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        related_name='comments',
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь который подписывается'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Пользователь на которого подписываются'
    )

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {
            'text': 'Текст подсказки',
            'group': 'Группа',
            'image': 'Картинка'
        }
        labels = {
            'group': 'Группа',
            'text': 'Текст подсказки'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {
            'text': 'Текст подсказки'
        }
        labels = {'text': 'Комментарий'}
        help_texts = {
            'text': 'Комментарий к посту'
        }


class PostCreateForm:
    pass

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

PAGINATOR_PAGE = 10


def get_page(request, post_list):
    paginator = Paginator(post_list, PAGINATOR_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.all()
    page_obj = get_page(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


@cache_page(60 * 20, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    page_obj = get_page(request, post_list)
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = request.user
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    page_obj = get_page(request, posts)
    following = user.is_authenticated and Follow.objects.filter(
        user=user, author=author
    ).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = PostForm(request.POST or None, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)
        return render(request, 'posts/post_create.html', context)
    return render(request, 'posts/post_create.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'is_edit': True,
        'form': form,
        'post': post}
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    author_following_posts = Post.objects.filter(
        author__following__user=user
    ).all()
    page_obj = get_page(request, author_following_posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Функция-обработчик, позволяющая подписаться на автора."""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        author.following.filter(user=user).delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title%}
Последние обновления на сайте
{% endblock%}

{% block content %}
{% load thumbnail %}
{% include 'includes/switcher.html' %}
<body>
<main>
    <h1>Посты авторов на которых подписан пользователь</h1>
    {% for post in page_obj %}
    <div class="container py-5">

        <div class="row">
            <div class="col">
                {% thumbnail post.image "400x400" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
                <div class="col">
                    <h1>
                        <font color="MidnightBlue">
                            <em>Текст поста: </em>
                        </font>
                    </h1>
                    <h2>{{ post.text }}</h2>
                </div>
                <ul>
                    <em>
                        <li>
                            <a href="{% url 'posts:profile' post.author.username %}">
                                Все посты пользователя {{ post.author.get_full_name|default:post.author.username }}
                            </a>
                        </li>
                        {% if post.group %}
                        <li>
                            <a href="{% url 'posts:group_list' post.group.slug %}">
                                Все записи группы {{ post.group }}
                            </a>
                        </li>
                        {% endif %}
                        <li>
                            Дата публикации: {{ post.pub_date|date:"d E Y" }}
                        </li>
                    </em>
                </ul>
            </div>
        </div>
    </div>
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
</main>
</body>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% block title%}
Группа: {{ group.title }}
{% endblock%}
{% block content %}
{% load thumbnail %}
<main>
    <div class="container py-5">
        <div class="row">
            <div class="col">
                <img src="{% static 'img/_Q.jpg' %}" width="200" height="200" align="middle"/>
            </div>
            <div class="col-6">
                <font color="MidnightBlue">
                    <em>
                        <h1><b> Все записи группы {{ group.description }}</b></h1>
                    </em>
                </font>
            </div>
            <div class="col">
                <img src="{% static 'img/ulitca.jpg' %}" width="170" height="170" align="middle"/>
            </div>
        </div>
    </div>
    {% for post in page_obj %}
    <div class="container py-5">
        <div class="row">
            <div class="col">
                {% thumbnail post.image "500x500" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
            </div>
            <div class="col">
                <h1>
                    <font color="MidnightBlue">
                        <em>Текст поста: </em>
                    </font>
                </h1>
                <h2>{{ post.text }}</h2>

            </div>
        </div>
        <br>
        <ul>
            <em>
                <li>
                    <a href="{% url 'posts:post_detail' post.id %}">
                        Все посты пользователя {{ post.author.get_full_name|default:post.author.username }}
                    </a>
                </li>
                {% if post.group %}
                <li>
                    <a href="{% url 'posts:group_list' post.group.slug %}">
                        Все записи группы {{ post.group }}
                    </a>
                </li>
                <li>
                    <a href="{% url 'posts:post_detail' post.id %}">Информация о посте</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                {% endif %}
            </em>
        </ul>
    </div>
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
</main>

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block title%}
Последние обновления на сайте
{% endblock%}
{% block content %}
{% load thumbnail %}
<main>
    <div class="container py-5">
        <div class="row">
            <div class="col">
                <img src="{% static 'img/colnce.jpg' %}" width="250" height="250" align="middle"/>
            </div>
            <div class="col-6">
                <font color="MidnightBlue">
                    <em>
                        <h1><b>Сайт хорошего настроения</b></h1>
                        <br>
                        <h2>Чем чаще мы улыбаемся, тем счастливее становимся! Японская пословица гласит: "Сильнейший
                            тот, кто улыбается."
                        </h2>
                        <h1>最強の
                            笑っている人ですか</h1>

                    </em>
                </font>
            </div>
            <div class="col">
                <img src="{% static 'img/babochka.jpg' %}" width="250" height="250" align="middle"/>
            </div>
        </div>
    </div>
    {% load cache %}
    {% cache 20 index_page page_odj.number %}
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
    <div class="container py-5">
        <div class="row">
            <div class="col">
                {% thumbnail post.image "500x500" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
            </div>
            <div class="col">
                <h1>
                    <font color="MidnightBlue">
                        <em>Текст поста: </em>
                    </font>
                </h1>
                <h2>{{ post.text }}</h2>
            </div>
            <ul>
                <em>
                    <li>
                        {% if post.group %}
                        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы {{ post.group }}
                        </a>
                        {% endif %}
                    </li>
                    <li>
                        <a href="{% url 'posts:post_detail' post.id %}">Все посты пользователя
                            {{post.author.get_full_name|default:post.author.username }}
                        </a>
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </em>
            </ul>
        </div>
    </div>
    {% if not forloop.last %}
    {% endif %}
    {% endfor %}
    {% endcache %}
</main>
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% if is_edit %}Редактировать запись {% else %} Добавить запись {% endif %}
{% load thumbnail %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <em>
            <div class="card">
                <div class="card-header">
                    {% if is_edit %}Редактировать запись
                    {% else %} Добавить запись
                    {% endif %}
                </div>
                <div class="card-body">
                    {# Этот блок будет показан, если в форме есть ошибки #}
                    {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row my-3 p-3">
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                <span class="required text-danger">*</span>
                                {% endif %}
                            </label>
                            {{ field }}
                            {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                {{ field.help_text|safe }}
                            </small>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <div class="form-group row my-3 p-3">
                        </div>
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {% if is_edit %}
                                Сохранить
                                {% else %}
                                Добавить
                                {% endif %}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </em>
    </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title%}
Пост {{post.text|truncatechars_html:30 }}
{% endblock%}
{% load thumbnail %}
{% block content %}
<body>
<main>
    <div class="container py-5">
        <div class="row">
            <div class="col">
                {% thumbnail post.image "500x500" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
                {% if post.group %}
                <ul>
                    <em>
                        <li>
                            <a href="{% url 'posts:group_list' post.group.slug %}">
                               Все записи группы {{ post.group }}
                            </a>
                        </li>
                        {% endif %}
                        <li>
                            <a href="{% url 'posts:profile' post.author.username %}">
                                Все посты пользователя {{ post.author.get_full_name|default:post.author.username }}
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'posts:post_edit' post.id %}">Редактировать пост</a>
                        </li>

                        <li>
                            Всего постов: {{ post.author.posts.count }}
                        </li>
                        <li>
                            Дата публикации: {{ post.pub_date|date:"d E Y" }}
                        </li>
                    </em>
                </ul>
            </div>
            <div class="col">
                <h1>
                    <font color="MidnightBlue">
                        <em>Текст поста: </em>
                    </font>
                </h1>
                <h2>{{ post.text }}</h2>
                {% include 'includes/commit.html' %}
            </div>
        </div>
    </div>
</main>
</body>
{% endblock %}

yatube/templates/posts/post_edit.html
{% extends "base.html" %}
{% block title %}
Редактировать запись
{% endblock %}
{% block content %}
<main>
    <div class="container py-5">
        <div class="row justify-content-center">
            {% with card_header='Редактировать пост' %}
            {% include 'users/includes/card.html' %}
            {% endwith %}
            <div class="card-body">
                <form method="post" action="../posts/post_edit.html">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                        {% if field.field.required %}
                        <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Добавить запись
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title%}
Профайл  пользователя {{user.username}}
{% endblock %}
{% block content %}
{% load thumbnail %}


<main>
    <form action="{% if is_edit %} {% url 'posts:post_edit' post.id %} {% endif %}"
          method="post">
        {% csrf_token %}
        <div class="mb-5">
            {% if following is True %}
            <a class="btn btn-lg btn-light"
               href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                Отписаться
            </a>
            {% elif following is False %}
            <a class="btn btn-lg btn-primary"
               href="{% url 'posts:profile_follow' author.username %}" role="button">
                Подписаться
            </a>
            {% endif %}
            <div class="container py-5">
                <div class="row">
                    <div class="col">
                        <img src="{% static 'img/6e8erscsb7w.jpg' %}" width="200" height="200" align="middle"/>
                    </div>
                    <div class="col-6">
                        <font color="MidnightBlue">
                            <h1><b>Все посты пользователя {{ user.username }}</b></h1>
                        </font>
                    </div>
                    <div class="col">
                        <img src="{% static 'img/25.png' %}" width="200" height="200" align="middle"/>
                    </div>
                </div>
            </div>
            {% load cache %}
            {% cache 20 index_page page_odj.number %}
            {% for post in page_obj %}
            <div class="container py-5">
                <div class="row">
                    <div class="col">
                        {% thumbnail post.image "400x400" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                    </div>
                    <div class="col">
                        <h1>
                            <font color="MidnightBlue">
                                <em>Текст поста: </em>
                            </font>
                        </h1>
                        <h2>{{ post.text }}</h2>
                    </div>
                </div>
            </div>
            <ul>
                <em>
                    <li>
                        {% if post.group %}
                        <a href="{% url 'posts:post_detail' post.id %}">Информация о посте</a>
                        {% endif %}
                    </li>
                    <li>
                        Автор: {{ post.author.get_full_name|default:post.author.username }}
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </em>
            </ul>
        </div>
    </form>
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
    {% endcache %}
</main>

{% endblock %}